### ISSUE TITLE
OMPL Import

### ISSUE THREAD

**Issue by fa72bd53** [Dalanie/SimpleNews#1]
Hi,
so I am absolutely not sure about this whole github thing and hope this post is not totally out of place ;)

Just installed SimpleNews on Android 4.4.2 and imported my feedly stuff which worked (pasted the content of the file). Just one thing I noticed:

It seemed that every time I imported the file (I did not quite understand how that worked till the 3rd time or so), the categories got all mixed up: their names and/or colours changed (I previously deleted all defaults and created new ones) to that of a default category and default feeds were added (even if not renamed). Each time only for some of them (though the first one seemed to get most of it).

Hope this is the correct place to report it! 

Thanks for a otherwise great reader! :)

**Comment by dlangerenken** [comment]
Thanks! This is the correct place - unfortunately I'm very busy right now but I try to fix this issue as soon as possible!

Cheers

**Comment by dlangerenken** [comment]
Should be fixed now!
